name: xerkonix_design_system
description: Flutter design system package for XERKONIX Weave UI tokens, themes, typography, and components.
version: 1.1.0
repository: https://github.com/xerkonix/xerkonix-flutter-library/tree/main/xerkonix-design-system
issue_tracker: https://github.com/xerkonix/xerkonix-flutter-library/issues

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: IBMPlexSansKR
      fonts:
        - asset: lib/fonts/ibm_plex_sans_kr/IBMPlexSansKR-Thin.ttf
          weight: 100
        - asset: lib/fonts/ibm_plex_sans_kr/IBMPlexSansKR-ExtraLight.ttf
          weight: 200
        - asset: lib/fonts/ibm_plex_sans_kr/IBMPlexSansKR-Light.ttf
          weight: 300
        - asset: lib/fonts/ibm_plex_sans_kr/IBMPlexSansKR-Regular.ttf
          weight: 400
        - asset: lib/fonts/ibm_plex_sans_kr/IBMPlexSansKR-Medium.ttf
          weight: 500
        - asset: lib/fonts/ibm_plex_sans_kr/IBMPlexSansKR-SemiBold.ttf
          weight: 600
        - asset: lib/fonts/ibm_plex_sans_kr/IBMPlexSansKR-Bold.ttf
          weight: 700
    - family: IBMPlexMono
      fonts:
        - asset: lib/fonts/ibm_plex_mono/IBMPlexMono-Thin.ttf
          weight: 100
        - asset: lib/fonts/ibm_plex_mono/IBMPlexMono-ExtraLight.ttf
          weight: 200
        - asset: lib/fonts/ibm_plex_mono/IBMPlexMono-Light.ttf
          weight: 300
        - asset: lib/fonts/ibm_plex_mono/IBMPlexMono-Regular.ttf
          weight: 400
        - asset: lib/fonts/ibm_plex_mono/IBMPlexMono-Medium.ttf
          weight: 500
        - asset: lib/fonts/ibm_plex_mono/IBMPlexMono-SemiBold.ttf
          weight: 600
        - asset: lib/fonts/ibm_plex_mono/IBMPlexMono-Bold.ttf
          weight: 700
