import 'dart:ui' show FontVariation;

import 'package:flutter/services.dart';

/// Loadable face for tactile `tokens.css` `--font` (v4.1) in CanvasKit.
///
/// Stack: **Pretendard Variable**, Pretendard, Inter, -apple-system,
/// BlinkMacSystemFont, Segoe UI, Apple SD Gothic Neo, Noto Sans CJK KR,
/// Malgun Gothic, sans-serif. CanvasKit cannot use system names — measured
/// 2026-09-20: declaration-only rasters match the engine default — so a
/// face is bundled.
///
/// Bundled file: **XK Sans KR** = a Modified Version (OFL 1.1) of
/// Pretendard Variable 1.3.9: KS X 1001 subset (2,350 Hangul + Latin /
/// digits / symbols), wght axis 400–600, no hinting — `lib/fonts/xk_sans_kr/`,
/// generated by `tools/build_pretendard_subset.py` (see SOURCE.txt). Under
/// 1 MB. The Pretendard licence reserves the name "Pretendard", so the font
/// and this [family] carry the name XK Sans KR; the OFL notices stay inside
/// the file and LICENSE.txt.
///
/// 450 / 550 are CSS weights. Flutter [FontWeight] has no those values.
/// The actual method is [FontVariation.weight] on this variable font; the
/// axis covers 400 · 450 · 500 · 550 · 600.
class XkTactileFonts {
  XkTactileFonts._();

  /// Family registered with [FontLoader] and written in every TextStyle.
  static const String family = 'XK Sans KR';

  static const String fileName = 'XKSansKR-ksx1001-w400-600.ttf';

  /// Directory the consume copy lives in, relative to the app root — the
  /// same string in pubspec `assets:`, in [assetPath] and in
  /// `tools/tactile_font_mirrors.json` (`asset_dir`). One layout for every
  /// app; `tools/sync_tactile_fonts.py --check` and the consumer-shape test
  /// lock it.
  static const String assetDir = 'assets/fonts/xk_sans_kr';

  /// Asset key of the app copy. On web requested as `assets/assets/fonts/…`.
  /// Kept out of FontManifest so first paint does not wait for it.
  static const String assetPath = '$assetDir/$fileName';

  /// Asset key when the file comes from this package's own bundle (apps that
  /// depend on the package by path, the example app). Flutter exposes
  /// `lib/fonts/…` of a package as `packages/<name>/lib/fonts/…`.
  static const String packageAssetPath =
      'packages/xerkonix_design_system/lib/fonts/xk_sans_kr/$fileName';

  static const String packageFilePath = 'lib/fonts/xk_sans_kr/$fileName';

  static bool _loaded = false;

  static bool get isLoaded => _loaded;

  static List<FontVariation> variations(double wght) {
    return <FontVariation>[FontVariation.weight(wght)];
  }

  /// Loads the face once. Tries [assetPathOverride] when given, otherwise
  /// the app copy [assetPath] and then the package bundle
  /// [packageAssetPath]. Returns false when neither has the bytes — the
  /// text then paints with the engine default, so apps should check the
  /// result in a test rather than assume.
  static Future<bool> ensureLoaded({String? assetPathOverride}) async {
    if (_loaded) {
      return true;
    }
    final List<String> keys = assetPathOverride != null
        ? <String>[assetPathOverride]
        : <String>[assetPath, packageAssetPath];
    for (final String key in keys) {
      try {
        final ByteData data = await rootBundle.load(key);
        if (data.lengthInBytes < 100 * 1024) {
          continue;
        }
        final FontLoader loader = FontLoader(family);
        loader.addFont(Future<ByteData>.value(data));
        await loader.load();
        _loaded = true;
        return true;
      } catch (_) {
        continue;
      }
    }
    return false;
  }

  /// Test / tool path: load official bytes without the asset bundle.
  /// Callers that have a [File] pass `ByteData.sublistView(file.readAsBytesSync())`.
  static Future<bool> loadFromBytes(ByteData data) async {
    if (data.lengthInBytes < 100 * 1024) {
      return false;
    }
    final FontLoader loader = FontLoader(family);
    loader.addFont(Future<ByteData>.value(data));
    await loader.load();
    _loaded = true;
    return true;
  }
}
