name: xerkonix_logger
description: Flutter logging package with log levels and emojis.
version: 1.1.0
repository: https://github.com/xerkonix/xerkonix-flutter-library/tree/main/xerkonix-logger
issue_tracker: https://github.com/xerkonix/xerkonix-flutter-library/issues

environment:
  sdk: '>=3.9.0 <4.0.0'
  flutter: '>=3.35.0'

dependencies:
  logger: ^2.7.0
  http: ^1.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
