#!/usr/bin/env python3
"""Official copy of the XK Sans KR face (Pretendard Variable KS X 1001 subset) + LICENSE + SOURCE.

Owner: xerkonix-flutter-library
Source: xerkonix-design-system/lib/fonts/xk_sans_kr/ (generated by
tools/build_pretendard_subset.py)

Apps keep their own ~0.8MB deploy copy (Docker/Railway cannot take a
runtime pub font). That duplication is the consume path, not a defect.
Hand copies without PROVENANCE.json are not a finished apply.

One layout for every app (locked here and by the Dart consumer-shape test):

    <app>/assets/fonts/xk_sans_kr/<files>      ← manifest "asset_dir"
    <app>/pubspec.yaml  flutter: assets: - assets/fonts/xk_sans_kr/

That directory string is XkTactileFonts.assetDir, so the loader's asset key
and the copy location cannot drift apart.

  python3 tools/sync_tactile_fonts.py --write --dest <app>/assets/fonts/xk_sans_kr
  python3 tools/sync_tactile_fonts.py --write --consumer cotact --workspace <ws>
  python3 tools/sync_tactile_fonts.py --check --consumer cotact --workspace <ws>
  python3 tools/sync_tactile_fonts.py --selftest
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
LIB_ROOT = HERE.parent
MANIFEST_NAME = "tactile_font_mirrors.json"
PROVENANCE_NAME = "PROVENANCE.json"
KIND = "xerkonix-tactile-font-consumer"
DART_FONTS = LIB_ROOT / "xerkonix-design-system" / "lib" / "src" / "tactile" / "tactile_fonts.dart"


def load_manifest() -> dict:
    return json.loads((HERE / MANIFEST_NAME).read_text(encoding="utf-8"))


def source_dir() -> Path:
    return (LIB_ROOT / load_manifest()["source"]).resolve()


def listed_files() -> list[str]:
    return list(load_manifest()["files"])


def asset_dir() -> str:
    return load_manifest()["asset_dir"]


def font_file() -> str:
    return next(name for name in listed_files() if name.endswith(".ttf"))


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def provenance_payload(files: list[str], src: Path) -> dict:
    out = {
        "kind": KIND,
        "owner": "xerkonix-flutter-library",
        "source": load_manifest()["source"],
        "generator": "tools/sync_tactile_fonts.py",
        "not": "tools/tactile_gate.json",
        "asset_dir": asset_dir(),
        "files": {},
    }
    for name in files:
        path = src / name
        out["files"][name] = {"sha256": sha256_file(path), "bytes": path.stat().st_size}
    return out


def copy_to(dest: Path) -> None:
    src = source_dir()
    files = listed_files()
    dest.mkdir(parents=True, exist_ok=True)
    for name in files:
        shutil.copyfile(src / name, dest / name)
    (dest / PROVENANCE_NAME).write_text(
        json.dumps(provenance_payload(files, src), indent=2) + "\n",
        encoding="utf-8",
    )


def app_root_of(dest: Path) -> Path | None:
    """<app>/assets/fonts/xk_sans_kr → <app>; None when the layout is wrong."""
    parts = Path(asset_dir()).parts
    if len(dest.parts) < len(parts) or tuple(dest.parts[-len(parts):]) != parts:
        return None
    return Path(*dest.parts[: len(dest.parts) - len(parts)])


def pubspec_declares(pubspec: Path) -> bool:
    """pubspec lists the directory (`assets/fonts/xk_sans_kr/`) or the font file itself."""
    text = pubspec.read_text(encoding="utf-8")
    wanted_dir = asset_dir().rstrip("/") + "/"
    wanted_file = f"{asset_dir()}/{font_file()}"
    for line in text.splitlines():
        m = re.match(r"\s*-\s*(\S+)\s*$", line)
        if m and m.group(1) in (wanted_dir, wanted_file):
            return True
    return False


def check_shape(dest: Path) -> list[str]:
    """The copy sits at <app>/assets/fonts/xk_sans_kr and the app's pubspec lists it."""
    errors: list[str] = []
    app = app_root_of(dest)
    if app is None:
        return [f"{dest}: 사본은 <app>/{asset_dir()} 에 둔다 — 로더 XkTactileFonts.assetDir 와 같은 경로"]
    pubspec = app / "pubspec.yaml"
    if not pubspec.is_file():
        return [f"{pubspec}: 앱 pubspec.yaml 이 없다"]
    if not pubspec_declares(pubspec):
        errors.append(
            f"{pubspec}: flutter.assets 에 `{asset_dir()}/` 가 없다 — 로더가 `{asset_dir()}/{font_file()}` 를 읽는다"
        )
    return errors


def check_dest(dest: Path, require_source: bool = False) -> list[str]:
    errors: list[str] = []
    proven_path = dest / PROVENANCE_NAME
    if not proven_path.is_file():
        return [
            f"{dest}: PROVENANCE.json 없음 — 손복사 3벌은 공식 폰트 소비가 아니다. "
            "tools/sync_tactile_fonts.py --write 로 재생성하라."
        ]
    try:
        proven = json.loads(proven_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return [f"{proven_path}: JSON 파싱 실패: {exc}"]
    if proven.get("kind") != KIND:
        errors.append(f"{proven_path}: kind 가 {KIND} 가 아니다")
    if proven.get("generator") != "tools/sync_tactile_fonts.py":
        errors.append(f"{proven_path}: generator 가 공식 복사기가 아니다")
    listed = listed_files()
    recorded = proven.get("files") or {}
    if sorted(recorded) != sorted(listed):
        errors.append(
            f"{dest}: provenance 파일 목록이 manifest 와 다름 "
            f"recorded={sorted(recorded)} expected={listed}"
        )
    for name in listed:
        path = dest / name
        if not path.is_file():
            errors.append(f"{path}: 소비 사본 없음")
            continue
        actual = sha256_file(path)
        expected = (recorded.get(name) or {}).get("sha256")
        if expected and actual != expected:
            errors.append(f"{path}: sha256 drift (local≠PROVENANCE)")
    src = source_dir()
    if src.is_dir():
        for name in listed:
            left = src / name
            right = dest / name
            if left.is_file() and right.is_file() and left.read_bytes() != right.read_bytes():
                errors.append(f"{right}: owner 원본과 바이트가 다름")
    elif require_source:
        errors.append(f"{src}: owner 원본을 찾지 못함")
    errors.extend(check_shape(dest))
    return errors


def resolve_consumer_dests(workspace: Path, consumer: str) -> list[Path]:
    known = load_manifest()["consumers"]
    if consumer not in known:
        raise SystemExit(f"unknown --consumer {consumer}; known: {', '.join(sorted(known))}")
    return [(workspace / consumer / known[consumer]["app"] / asset_dir()).resolve()]


def dart_asset_dir() -> str | None:
    m = re.search(r"static const String assetDir = '([^']+)';", DART_FONTS.read_text(encoding="utf-8"))
    return m.group(1) if m else None


def dart_file_name() -> str | None:
    m = re.search(r"static const String fileName = '([^']+)';", DART_FONTS.read_text(encoding="utf-8"))
    return m.group(1) if m else None


def selftest() -> int:
    src = source_dir()
    files = listed_files()
    missing = [name for name in files if not (src / name).is_file()]
    if missing:
        print("selftest FAIL source missing", missing, file=sys.stderr)
        return 1
    if dart_asset_dir() != asset_dir() or dart_file_name() != font_file():
        print(
            f"selftest FAIL loader≠manifest: XkTactileFonts.assetDir={dart_asset_dir()!r} fileName={dart_file_name()!r} "
            f"vs manifest asset_dir={asset_dir()!r} file={font_file()!r}",
            file=sys.stderr,
        )
        return 1
    with tempfile.TemporaryDirectory() as tmp:
        for consumer, spec in load_manifest()["consumers"].items():
            app = Path(tmp) / consumer / spec["app"]
            app.mkdir(parents=True, exist_ok=True)
            (app / "pubspec.yaml").write_text(
                f"name: {consumer.replace('-', '_')}_app\nflutter:\n  assets:\n    - {asset_dir()}/\n",
                encoding="utf-8",
            )
            dest = resolve_consumer_dests(Path(tmp), consumer)[0]
            copy_to(dest)
            errs = check_dest(dest, require_source=True)
            if errs:
                print(f"selftest FAIL after write ({consumer})", errs, file=sys.stderr)
                return 1
            (app / "pubspec.yaml").write_text("name: x\nflutter:\n  assets:\n    - fonts/other/\n", encoding="utf-8")
            if not check_dest(dest):
                print(f"selftest FAIL pubspec drift not detected ({consumer})", file=sys.stderr)
                return 1
            (app / "pubspec.yaml").write_text(f"name: x\nflutter:\n  assets:\n    - {asset_dir()}/\n", encoding="utf-8")
            (dest / "LICENSE.txt").write_text("drifted\n", encoding="utf-8")
            if not check_dest(dest):
                print(f"selftest FAIL byte drift not detected ({consumer})", file=sys.stderr)
                return 1
            (dest / PROVENANCE_NAME).unlink()
            if not check_dest(dest):
                print(f"selftest FAIL missing provenance not detected ({consumer})", file=sys.stderr)
                return 1
        wrong = Path(tmp) / "x" / "assets" / "fonts" / "elsewhere"
        copy_to(wrong)
        if not any("assetDir" in e for e in check_dest(wrong)):
            print("selftest FAIL wrong directory not detected", file=sys.stderr)
            return 1
    print("selftest OK")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--selftest", action="store_true")
    parser.add_argument("--dest", type=Path)
    parser.add_argument("--consumer")
    parser.add_argument("--workspace", type=Path)
    args = parser.parse_args()
    if args.write and args.check:
        parser.error("choose --write or --check")
    if args.selftest:
        return selftest()
    dests: list[Path] = []
    if args.dest:
        dests.append(args.dest.resolve())
    if args.consumer:
        workspace = (args.workspace or LIB_ROOT.parent).resolve()
        dests.extend(resolve_consumer_dests(workspace, args.consumer))
    if args.write:
        if not dests:
            parser.error("--write requires --dest or --consumer")
        for dest in dests:
            copy_to(dest)
            print(f"wrote {dest}")
            for item in check_shape(dest):
                print(f"주의: {item}", file=sys.stderr)
        return 0
    if args.check:
        if not dests:
            parser.error("--check requires --dest or --consumer")
        errors: list[str] = []
        for dest in dests:
            errors.extend(check_dest(dest))
        if errors:
            for item in errors:
                print(item, file=sys.stderr)
            return 1
        print(f"tactile font mirrors: {len(dests)} dests; differences: 0; shape OK")
        return 0
    parser.error("choose --write, --check, or --selftest")


if __name__ == "__main__":
    raise SystemExit(main())
